version: '3.4'
services:
    db:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - app-net
      expose:
        - "6543"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: newcredit
      volumes:
        - postgres-data:/var/lib/postgresql/data
      restart: unless-stopped
    newcredit-service:
      image: newcredit-service
      depends_on:
        - db
        - newcredit-engine
      ports:
        - 8080:8080
      networks:
        - app-net
      build:
        context: ./back-end/newcredit/
        dockerfile: Dockerfile
      restart: unless-stopped
    newcredit-engine:
      image: newcredit-engine
      ports:
        - 8081:8081
      networks:
        - app-net
      build:
        context: ./back-end/newcredit-engine/
        dockerfile: Dockerfile
      restart: unless-stopped
    newcredit-ui:
      image: newcredit-ui
      depends_on:
        - newcredit-service
      ports:
        - 4200:80
      networks:
        - app-net
      build:
        context: ./front-end/
        dockerfile: Dockerfile
      restart: unless-stopped
volumes:
  postgres-data:        

networks:
  app-net:
