server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://0.0.0.0:5432/newcredit?createDatabaseIfNotExist=trues
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  newCreditEngine:
    url: http://0.0.0.0:8081/api/proposal-reviews

---

spring:
  profiles:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/newcredit?createDatabaseIfNotExist=trues
application:
  newCreditEngine:
    url: http://newcredit-engine:8081/api/proposal-reviews